# Generated by Django 5.1 on 2024-08-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='foto',
            field=models.ImageField(default='default.png', upload_to='recetas'),
        ),
    ]
