# Generated by Django 5.1 on 2024-08-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_alter_receta_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='foto',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
