# Generated by Django 5.1 on 2024-08-24 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersmetadata',
            options={'verbose_name': 'User metadata', 'verbose_name_plural': 'User metadata'},
        ),
        migrations.AlterModelTable(
            name='usersmetadata',
            table='users_metadata',
        ),
    ]
